### ISSUE TITLE
convert EpiData logical

### ISSUE THREAD

**Issue by charlesknightsbridge** [daudi/Epidata-XML-to-R#1]
Hi David,
Logical type is not well documented

Field type = 0
Can have values "Y", "N" or be blank (system missing); value labels not allowed as far as I know.

conversion code:

  } else if (fld.type == 0){
    ## Logical - empty to NA, Y to TRUE, else to FALSE 
    x[x==""] <- NA
    x <- x=="Y"

Jamie

**Comment by daudi** [comment]
Thanks. I've just added this.
